<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="ENCODER2ANGLE" Id="{8f1b6799-8175-42cd-a06b-61058091be48}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ENCODER2ANGLE
VAR_INPUT RETAIN
	encoder_in : UDINT;
	encoder_in_reference : UDINT;
END_VAR
VAR_OUTPUT RETAIN
	enc_angle : REAL;
END_VAR
VAR
	pulsos : UDINT:=600;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[///Medir ángulos
enc_angle:= 2*GVL.Pi - ((encoder_in-encoder_in_reference) MOD Pulsos)*2*GVL.Pi/Pulsos;]]></ST>
    </Implementation>
    <LineIds Name="ENCODER2ANGLE">
      <LineId Id="22" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>