<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_SOLVEXY" Id="{fa1b62a0-c717-4454-9065-b5fc8a73063a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SOLVEXY
VAR_INPUT
x : REAL;
y : REAL;
END_VAR
VAR_OUTPUT
alfa : REAL;
beta : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[alfa := ATAN(y/(GVL.d-x)) + ACOS ( (y*y + (x-GVL.d)*(x-GVL.d) + GVL.l1*GVL.l1 - GVL.l2*GVL.l2 ) / ( 2*GVL.l1*GVL.l2) );
beta := GVL.Pi - ATAN(y/(x-GVL.d)) - ACOS ( (y*y + (x-GVL.d)*(x-GVL.d) + GVL.l1*GVL.l1 - GVL.l2*GVL.l2 ) / ( 2*GVL.l1*GVL.l2) );]]></ST>
    </Implementation>
    <LineIds Name="FB_SOLVEXY">
      <LineId Id="16" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>