<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="LetraPresente" Id="{50075678-603b-4616-8323-5471aeed9a5a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION LetraPresente : BOOL
VAR_INPUT
	letra: STRING;
	cadena: STRING;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[LetraPresente := FIND (cadena,letra) > 0;]]></ST>
    </Implementation>
    <LineIds Name="LetraPresente">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>